# Project: Project1
# Compiler: Default GCC compiler
# Compiler Type: MingW 3
# Makefile created by wxDev-C++ IDE 7.4.2.569 on 25/11/13 15:23

WXLIBNAME = wxmsw29u
CPP       = g++.exe
CC        = gcc.exe
WINDRES   = "windres.exe"
OBJ       = Objects/MingW/testApp.o Objects/MingW/testDlg.o Objects/MingW/InterviewDlg.o Objects/MingW/test_private.res
LINKOBJ   = "Objects/MingW/testApp.o" "Objects/MingW/testDlg.o" "Objects/MingW/InterviewDlg.o" Objects/MingW/test_private.res
LIBS      = -L"E:/wxDevCpp/wxDevCppP7-64b/App/devcpp/lib/wx/gcc_lib" -L"E:/wxDevCpp/wxDevCppP7-64b/App/devcpp/lib" -L"E:/wxDevCpp/wxDevCppP7-64b/App/devcpp/MinGW32/lib" -mwindows -l$(WXLIBNAME) -l$(WXLIBNAME)_gl -lwxscintilla -lwxtiff -lwxjpeg -lwxpng -lwxzlib -lwxregexu -lwxexpat -lkernel32 -luser32 -lgdi32 -lcomdlg32 -lwinspool -lwinmm -lshell32 -lcomctl32 -lole32 -loleaut32 -luuid -lrpcrt4 -ladvapi32 -lwsock32 -lodbc32 -lopengl32  
INCS      = -I"E:/wxDevCpp/wxDevCppP7-64b/App/devcpp/MinGW32/include"
CXXINCS   = -I"E:/wxDevCpp/wxDevCppP7-64b/App/devcpp/MinGW32/include" -I"E:/wxDevCpp/wxDevCppP7-64b/App/devcpp/" -I"E:/wxDevCpp/wxDevCppP7-64b/App/devcpp/include/common" -I"E:/wxDevCpp/wxDevCppP7-64b/App/devcpp/include"
RCINCS    = --include-dir "E:/wxDevCpp/WXDEVC~1/App/devcpp/include/common"
BIN       = Output/MingW/test.exe
DEFINES   = -D__WXMSW__ -D__GNUWIN32__ -D_UNICODE
CXXFLAGS  = $(CXXINCS) $(DEFINES)  
CFLAGS    = $(INCS) $(DEFINES)  
GPROF     = gprof.exe
ifeq ($(OS),Windows_NT)
   RM = del /Q
   FixPath = $(subst /,\,$1)
else
   RM = rm -f
   FixPath = $1
endif
LINK      = g++.exe

.PHONY: all all-before all-after clean clean-custom
all: all-before $(BIN) all-after

clean: clean-custom
	$(RM) $(call FixPath,$(LINKOBJ)) "$(call FixPath,$(BIN))"

$(BIN): $(OBJ)
	$(LINK) $(LINKOBJ) -o "$(BIN)" $(LIBS) 

Objects/MingW/testApp.o: $(GLOBALDEPS) testApp.cpp testApp.h testDlg.h InterviewDlg.h
	$(CPP) -c testApp.cpp -o Objects/MingW/testApp.o $(CXXFLAGS)

Objects/MingW/testDlg.o: $(GLOBALDEPS) testDlg.cpp testDlg.h
	$(CPP) -c testDlg.cpp -o Objects/MingW/testDlg.o $(CXXFLAGS)

Objects/MingW/InterviewDlg.o: $(GLOBALDEPS) InterviewDlg.cpp InterviewDlg.h
	$(CPP) -c InterviewDlg.cpp -o Objects/MingW/InterviewDlg.o $(CXXFLAGS)

Objects/MingW/test_private.res: Objects/MingW/test_private.rc testApp.rc 
	$(WINDRES) --input-format=rc -o Objects/MingW/test_private.res $(RCINCS) Objects/MingW/TEST_P~1.RC -O coff
